// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

void* winrt_make_PhotoEdit_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::PhotoEdit::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::PhotoEdit
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<PhotoEdit::implementation::XamlMetaDataProvider>())
    {
    }
}
